[package]
name = "EvolveUnpaker"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = { path = "zip2" }
thirtyfour = "0.35.0"
arboard = "3.5.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
enigo = "0.5.0"
